# Static configuration
api:
  dashboard: true
  insecure: true

pilot:
  token: 11111111-1111-1111-1111-111111111111

log:
  level: DEBUG

experimental:
  devPlugin:
    goPath: /home/traefik/go/
    moduleName: traefik/plugindemo

entryPoints:
  http:
    address: ":4000"
    forwardedHeaders:
      insecure: true

providers:
  file:
    filename: dynamic-dev-config.yml